apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service
  description: This is a demo service
  tags:
    - nodejs
    - backend
spec:
  type: service
  lifecycle: production
  owner: team
