apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service3_feature1
  description: This is a private demo service
  tags:
    - nodejs
    - backend
spec:
  type: service
  lifecycle: dev
  owner: team
